---
# file: site.yml

# run like: ansible-playbook -b -i inventory --limit basement site.yml
# see https://unix.stackexchange.com/questions/113754/allow-user1-to-su-user2-without-password

- hosts: all

# simple ping to test hosts
- name: See the server's configuration
  hosts: all
  roles:
    - server_settings    

- name: Set up docker machines
  hosts: docker
  roles:
    - common   
