---
# file: roles/common/main.yml

# Testing
- name: Debug package variable
  debug: 
    msg: "This is the package {{ item }}"
  with_items: "{{ package }}"

# Install software
- name: Install software
  pacman:
    update_cache: yes
    name: "{{ package }}"
    state: present
  become: true 
# Deprecated  with_items: "{{ package }}"
  
# Start service:

# Enable service:
