---
# file: tools/test.yml

# to run use this from the root directory of the ansible project:
# ansible-playbook -i inventory tools/test.yml

# having trouble printing out debug messages in site.yml,
# found this snippet to test from
# https://docs.ansible.com/ansible/latest/network/getting_started/first_playbook.html
# which didn't work ... ansible_net_hostname is undefined

- name: Test out ansible and debug messaging
  hosts: all
  tasks:
    
    - name: See what variables are available
      debug: var=ansible_facts

    - name: Display the config
      debug: 
#BROKEN >        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
        msg: "The hostname is {{ ansible_hostname }} and the OS family is {{ ansible_os_family }}"
